# GoReleaser configuration for Radar
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    # Build frontend before Go compilation (gets embedded)
    - sh -c "cd web && npm install && npm run build"
    - mkdir -p internal/static/dist
    - sh -c "cp -r web/dist/* internal/static/dist/"

builds:
  - id: radar
    main: ./cmd/explorer
    binary: kubectl-radar
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE*
      - README*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: skyhook-io
    name: radar
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  header: |
    ## Radar v{{.Version}}

    **Modern Kubernetes visibility.** Local-first. No account. No cloud dependency. Fast.

    Topology, event timeline, and service traffic — plus resource browsing and Helm management. Open source. Free forever.

    ### Installation

    **Homebrew:**
    ```bash
    brew tap skyhook-io/tap
    brew install radar
    ```

    **Manual (macOS Apple Silicon):**
    ```bash
    curl -LO https://github.com/skyhook-io/radar/releases/download/v{{.Version}}/radar_{{.Version}}_darwin_arm64.tar.gz
    tar -xzf radar_{{.Version}}_darwin_arm64.tar.gz
    sudo mv kubectl-radar /usr/local/bin/
    ```

    **Manual (macOS Intel):**
    ```bash
    curl -LO https://github.com/skyhook-io/radar/releases/download/v{{.Version}}/radar_{{.Version}}_darwin_amd64.tar.gz
    tar -xzf radar_{{.Version}}_darwin_amd64.tar.gz
    sudo mv kubectl-radar /usr/local/bin/
    ```

    **Manual (Linux amd64):**
    ```bash
    curl -LO https://github.com/skyhook-io/radar/releases/download/v{{.Version}}/radar_{{.Version}}_linux_amd64.tar.gz
    tar -xzf radar_{{.Version}}_linux_amd64.tar.gz
    sudo mv kubectl-radar /usr/local/bin/
    ```

    Then run: `kubectl radar`

# Homebrew formula (publishes to skyhook-io/homebrew-tap)
brews:
  - name: radar
    repository:
      owner: skyhook-io
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/skyhook-io/radar"
    description: "Modern Kubernetes visibility — topology, traffic, and Helm management"
    license: "Apache-2.0"
    install: |
      bin.install "kubectl-radar"
    test: |
      system "#{bin}/kubectl-radar", "--version"
